version: "3.6"

services:
  server:
    build: ./server
    container_name: server
    environment:
      PORT: 4000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: backend-block
    ports:
      - "4001:4000"
    links:
      - mongodb
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    environment:
      REACT_APP_API_ENDPOINT: http://localhost:4001/api
    ports:
      - "3001:3000"
    links:
      - server
    networks:
      - app-network
      
  mongodb:
    container_name: "mongodb"
    image: mongo:4.2.3-bionic
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - fullStackBackendDB:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
  
volumes:
  fullStackBackendDB:
    external: true